"""initial_schema

Revision ID: a5bfb4c64f04
Revises: 
Create Date: 2026-06-26 15:52:51.741593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5bfb4c64f04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('attach_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_entity_type'), ['entity_type'], unique=False)

    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isbn13', sa.String(length=20), nullable=True),
    sa.Column('isbn10', sa.String(length=20), nullable=True),
    sa.Column('asin', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('normalized_title', sa.String(length=500), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('translators', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('publish_date', sa.String(length=20), nullable=True),
    sa.Column('edition', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('cover_path', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('google_books_id', sa.String(length=50), nullable=True),
    sa.Column('openlibrary_id', sa.String(length=50), nullable=True),
    sa.Column('goodreads_id', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_isbn13'), ['isbn13'], unique=True)
        batch_op.create_index(batch_op.f('ix_books_normalized_title'), ['normalized_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_title'), ['title'], unique=False)

    op.create_table('custom_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_fields'))
    )
    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_fields_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_fields_entity_type'), ['entity_type'], unique=False)

    op.create_table('members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('avatar_path', sa.String(length=500), nullable=True),
    sa.Column('channel_bindings', sa.Text(), nullable=True),
    sa.Column('reading_streak_offset', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('book_copies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('copy_type', sa.String(length=20), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('owner_member_id', sa.Integer(), nullable=True),
    sa.Column('acquire_type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_copies_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_member_id'], ['members.id'], name=op.f('fk_book_copies_owner_member_id_members'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_copies'))
    )
    with op.batch_alter_table('book_copies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_copies_book_id'), ['book_id'], unique=False)

    op.create_table('book_tags',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_tags_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_book_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'tag_id', name=op.f('pk_book_tags')),
    sa.UniqueConstraint('book_id', 'tag_id', name='uq_book_tags_book_tag')
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_operation_logs_member_id_members'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_logs'))
    )
    op.create_table('reading_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.String(length=10), nullable=False),
    sa.Column('pages_read', sa.Integer(), nullable=False),
    sa.Column('minutes_read', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('session_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_reading_logs_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_reading_logs_member_id_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_logs'))
    )
    with op.batch_alter_table('reading_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_logs_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_logs_log_date'), ['log_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_logs_member_id'), ['member_id'], unique=False)

    op.create_table('reading_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(length=20), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('chapter', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_reading_notes_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_reading_notes_member_id_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_notes'))
    )
    with op.batch_alter_table('reading_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_notes_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_notes_member_id'), ['member_id'], unique=False)

    op.create_table('reading_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('to_read', sa.Boolean(), nullable=False),
    sa.Column('owned', sa.Boolean(), nullable=False),
    sa.Column('borrowed', sa.Boolean(), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=True),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.Column('personal_notes', sa.Text(), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('finish_date', sa.String(length=20), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_reading_progress_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_reading_progress_member_id_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_progress')),
    sa.UniqueConstraint('book_id', 'member_id', name='uq_reading_progress_book_member')
    )
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_progress_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_progress_member_id'), ['member_id'], unique=False)

    op.create_table('purchase_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('copy_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('order_no', sa.String(length=100), nullable=True),
    sa.Column('seller', sa.String(length=200), nullable=True),
    sa.Column('buyer_member_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_purchase_records_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyer_member_id'], ['members.id'], name=op.f('fk_purchase_records_buyer_member_id_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['copy_id'], ['book_copies.id'], name=op.f('fk_purchase_records_copy_id_book_copies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_records'))
    )
    with op.batch_alter_table('purchase_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_records_book_id'), ['book_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_records_book_id'))

    op.drop_table('purchase_records')
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_progress_member_id'))
        batch_op.drop_index(batch_op.f('ix_reading_progress_book_id'))

    op.drop_table('reading_progress')
    with op.batch_alter_table('reading_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_notes_member_id'))
        batch_op.drop_index(batch_op.f('ix_reading_notes_book_id'))

    op.drop_table('reading_notes')
    with op.batch_alter_table('reading_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_logs_member_id'))
        batch_op.drop_index(batch_op.f('ix_reading_logs_log_date'))
        batch_op.drop_index(batch_op.f('ix_reading_logs_book_id'))

    op.drop_table('reading_logs')
    op.drop_table('operation_logs')
    op.drop_table('book_tags')
    with op.batch_alter_table('book_copies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_copies_book_id'))

    op.drop_table('book_copies')
    op.drop_table('tags')
    op.drop_table('members')
    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_fields_entity_type'))
        batch_op.drop_index(batch_op.f('ix_custom_fields_entity_id'))

    op.drop_table('custom_fields')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_title'))
        batch_op.drop_index(batch_op.f('ix_books_normalized_title'))
        batch_op.drop_index(batch_op.f('ix_books_isbn13'))

    op.drop_table('books')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_entity_type'))
        batch_op.drop_index(batch_op.f('ix_attachments_entity_id'))

    op.drop_table('attachments')
    # ### end Alembic commands ###
