import { describe,it,expect,vi,beforeEach } from 'vitest'
import { mount,flushPromises } from '@vue/test-utils'
import { createPinia,setActivePinia } from 'pinia'
import { defineComponent,ref } from 'vue'
import Picker from '@/components/PlacementTargetPicker.vue'
import Provision from '@/components/CopyProvisionForm.vue'
import ShelfView from '@/views/StorageShelfView.vue'
import StorageView from '@/views/StorageView.vue'
import PlacementEditor from '@/components/CopyPlacementEditor.vue'
import { sessionRole } from '@/stores/session'
import { useMembersStore } from '@/stores/members'
const TS='2026-10-06T00:00:00Z'
const stats={assigned_copies:0,present_copies:0,on_shelf_copies:0,books_involved:0}
const room=(id=1,version=1,name='房间'+id)=>({id,code:'R'+id,name,description:null,sort_order:0,version,archived_at:null,created_at:TS,updated_at:TS,stats})
const shelf=(id=11)=>({id,room_id:1,code:'S'+id,name:'书架'+id,position_note:null,sort_order:0,version:1,archived_at:null,created_at:TS,updated_at:TS})
const detail=(id=11)=>({...shelf(id),stats,photos:[],layers:[{id:id*10,shelf_id:id,label:'层'+id,sort_order:0,version:1,archived_at:null,created_at:TS,updated_at:TS,cells:[{id:id*100,shelf_id:id,layer_id:id*10,label:'格'+id,code:'C'+id,version:1,sort_order:0,archived_at:null,created_at:TS,updated_at:TS}]}]})
const res=(data:any,status=200):Response=>({ok:status<300,status,json:async()=>status<300?{ok:true,data}:{detail:data}} as Response)
const deferred=()=>{let resolve!:(x:Response)=>void;const promise=new Promise<Response>(r=>resolve=r);return {resolve,promise}}
const link={props:['to'],template:'<a><slot/></a>'}
function pickerFetch(handler:(url:string)=>Response|Promise<Response>){vi.stubGlobal('fetch',vi.fn(async(input)=>handler(String(input))))}
function basePicker(url:string){if(url.includes('/storage/rooms'))return res({items:[room(1),room(2)],total:2});if(url.includes('room_id='))return res({items:[shelf(11),shelf(12)],total:2});throw Error(url)}
function provisionMount(){const pinia=createPinia();setActivePinia(pinia);useMembersStore().members=[{id:3,name:'爸爸',role:'member',avatar_path:null,reading_streak_offset:0,created_at:TS,updated_at:TS}];return {pinia,global:{plugins:[pinia],stubs:{PlacementTargetPicker:{template:'<button type="button" data-target @click="$emit(\'update:target\', {shelf_id:11,cell_id:null})">target</button>'}}}}}
async function fill(w:any,count='1'){await w.get('[data-field="owner"]').setValue('3');await w.get('[data-field="count"]').setValue(count);await w.get('[data-target]').trigger('click')}
function bodies(){return vi.mocked(fetch).mock.calls.filter(([,o])=>o?.method==='POST').map(([,o])=>JSON.parse(String(o?.body)))}
describe('只读复核边界探针：断言目前实际错误',()=>{
beforeEach(()=>{sessionRole.value='owner';vi.stubGlobal('fetch',vi.fn())})
it('BUG304：书架清空后旧详情晚到，空选项下仍出现旧层格',async()=>{const old=deferred();pickerFetch(u=>u.includes('/storage/shelves/11')?old.promise:basePicker(u));const w=mount(Picker);await flushPromises();await w.get('[data-field="room"]').setValue(1);await flushPromises();await w.get('[data-field="shelf"]').setValue(11);await w.get('[data-field="shelf"]').setValue('');old.resolve(res(detail()));await flushPromises();expect((w.get('[data-field="shelf"]').element as HTMLSelectElement).value).toBe('');expect(w.get('[data-field="layer"]').text()).toContain('层11');console.log('BUG304 clear shelf: shelf empty, old layer11 rendered')})
it('BUG304：A架详情挂起换房间B，旧层格被注入B选择器',async()=>{const old=deferred();pickerFetch(u=>u.includes('/storage/shelves/11')?old.promise:basePicker(u));const w=mount(Picker);await flushPromises();await w.get('[data-field="room"]').setValue(1);await flushPromises();await w.get('[data-field="shelf"]').setValue(11);await w.get('[data-field="room"]').setValue(2);await flushPromises();old.resolve(res(detail()));await flushPromises();expect((w.get('[data-field="room"]').element as HTMLSelectElement).value).toBe('2');expect(w.get('[data-field="layer"]').text()).toContain('层11');console.log('BUG304 cross room: room2 selected, old shelf11 layer rendered')})
it('BUG304：房间清空不取消书架请求，再选房间时旧架选项闪现',async()=>{const a=deferred(),b=deferred();pickerFetch(u=>u.includes('room_id=1')?a.promise:u.includes('room_id=2')?b.promise:basePicker(u));const w=mount(Picker);await flushPromises();await w.get('[data-field="room"]').setValue(1);await w.get('[data-field="room"]').setValue('');a.resolve(res({items:[shelf(99)],total:1}));await flushPromises();expect((w.vm as any).$.setupState.shelves[0].id).toBe(99);console.log('BUG304 clear room: stale shelf99 restored into setup state while room empty')})
it('BUG299：服务端提交但响应丢失→取消重开→同载荷新键重建',async()=>{const accepted=new Set<string>();let created=0;vi.mocked(fetch).mockImplementation(async(_,o)=>{const p=JSON.parse(String(o?.body));if(!accepted.has(p.idempotency_key)){accepted.add(p.idempotency_key);created+=p.items[0].new_copies.count}throw new TypeError('response lost')});const opts=provisionMount();const host=defineComponent({components:{Provision},setup(){return {open:ref(true)}},template:'<Provision v-if="open" :book-id="7" @close="open=false"/><button data-open @click="open=true">open</button>'});const w=mount(host,{global:opts.global});await fill(w);await w.get('form').trigger('submit');await flushPromises();await w.findAll('button').find(b=>b.text()==='取消')!.trigger('click');expect(w.findComponent(Provision).exists()).toBe(false);await w.get('[data-open]').trigger('click');await fill(w);await w.get('form').trigger('submit');await flushPromises();expect(bodies()[0].items).toEqual(bodies()[1].items);expect(bodies()[0].idempotency_key).not.toBe(bodies()[1].idempotency_key);expect(created).toBe(2);console.log('BUG299 reopen: same payload different keys, modeled atomic backend created=2')})
it('BUG299：响应丢失后A→B→A，最后A忘记首次未确认键',async()=>{vi.mocked(fetch).mockRejectedValue(new TypeError('response lost'));const opts=provisionMount();const w=mount(Provision,{props:{bookId:7},global:opts.global});await fill(w);await w.get('form').trigger('submit');await flushPromises();await w.get('[data-field="count"]').setValue('2');await w.get('form').trigger('submit');await flushPromises();await w.get('[data-field="count"]').setValue('1');await w.get('form').trigger('submit');await flushPromises();const p=bodies();expect(p[0].items).toEqual(p[2].items);expect(p[0].idempotency_key).not.toBe(p[2].idempotency_key);console.log('BUG299 A-B-A: identical first and third payload use distinct keys')})
it('BUG306：新路由详情失败，仍显示旧架但上传给新架ID',async()=>{vi.mocked(fetch).mockImplementation(async(u,o)=>{const url=String(u);if(o?.method==='POST')return res({});if(url.includes('/storage/shelves/22'))return res({code:'NOT_FOUND',message:'书架22不可见'},404);if(url.includes('/storage/shelves/11'))return res(detail());if(url.includes('/copies'))return res({items:[],total:0});throw Error(url)});const w=mount(ShelfView,{props:{shelfId:11,cell:null},global:{stubs:{RouterLink:link}}});await flushPromises();await w.setProps({shelfId:22});await flushPromises();expect(w.get('h1').text()).toContain('书架11');expect(w.get('[role="alert"]').text()).toContain('书架22不可见');const input=w.get('[data-field="photo-file"]');Object.defineProperty(input.element,'files',{value:[new File(['x'],'photo.jpg',{type:'image/jpeg'})],configurable:true});await input.trigger('change');await w.get('.upload-form').trigger('submit');await flushPromises();const call=vi.mocked(fetch).mock.calls.find(([,o])=>o?.method==='POST');expect(String(call?.[0])).toContain('/storage/shelves/22/photos');console.log('BUG306 failed navigation: h1 shelf11 with POST shelf22/photos')})
it('BUG305：409刷新期间仍可编辑，晚到回填清空用户新草稿',async()=>{const refresh=deferred();let gets=0;vi.mocked(fetch).mockImplementation(async(u,o)=>{const url=String(u);if(o?.method==='PATCH')return res({code:'PLACEMENT_CHANGED',message:'冲突'},409);if(url.includes('/storage/rooms')){gets++;return gets===1?res({items:[room()],total:1}):refresh.promise}if(url.includes('/storage/shelves?'))return res({items:[],total:0});throw Error(url)});const w=mount(StorageView,{global:{stubs:{RouterLink:link}}});await flushPromises();await w.get('[data-room="1"] button').trigger('click');await w.get('[data-field="name"]').setValue('首次修改');await w.get('.storage-form').trigger('submit');await flushPromises();expect((w.get('.storage-form button[type="submit"]').element as HTMLButtonElement).disabled).toBe(false);await w.get('[data-field="name"]').setValue('刷新期间的新草稿');refresh.resolve(res({items:[room(1,2,'服务端房间')],total:1}));await flushPromises();expect((w.get('[data-field="name"]').element as HTMLInputElement).value).toBe('服务端房间');console.log('BUG305 async refresh: enabled form new draft overwritten by remote name')})
it('BUG307：正确await延迟响应的格子切换确实丢弃旧册清单',async()=>{const old=deferred();const two={...detail(),layers:[{...detail().layers[0],cells:[detail().layers[0].cells[0],{...detail().layers[0].cells[0],id:1200}]}]};vi.mocked(fetch).mockImplementation(async(u)=>{const url=String(u);if(url.includes('/storage/shelves/11'))return res(two);if(url.includes('limit=1&'))return res({items:[],total:1});if(url.includes('/cells/1100/'))return old.promise;if(url.includes('/cells/1200/'))return res({items:[{copy_id:2,book_id:2,book_title:'新格册',status:'in_shelf',owner_member_id:null}],total:1});throw Error(url)});const w=mount(ShelfView,{props:{shelfId:11,cell:null},global:{stubs:{RouterLink:link}}});await flushPromises();await w.get('[data-cell-id="1100"]').trigger('click');await w.get('[data-cell-id="1200"]').trigger('click');await flushPromises();expect(w.text()).toContain('新格册');old.resolve(res({items:[{copy_id:1,book_id:1,book_title:'旧格册',status:'in_shelf',owner_member_id:null}],total:1}));await flushPromises();expect(w.text()).toContain('新格册');expect(w.text()).not.toContain('旧格册');console.log('BUG307 actual awaited delay: old page discarded, new selected cell retained')})
it('BUG303：往返模式后隐藏目标清零；发出的JSON在在途改值后保持快照',async()=>{const pending=deferred();vi.mocked(fetch).mockReturnValue(pending.promise);const w=mount(PlacementEditor,{props:{bookId:7,copy:{id:1,placement_version:3,placement:null} as any},global:provisionMount().global});await w.get('[data-target]').trigger('click');await w.get('[data-field="mode-clear"]').setValue();await w.get('[data-field="mode-set"]').setValue();await w.get('form').trigger('submit');expect(vi.mocked(fetch)).not.toHaveBeenCalled();expect(w.text()).toContain('请先选择目标书架');await w.get('[data-target]').trigger('click');await w.get('form').trigger('submit');const payload=JSON.parse(String(vi.mocked(fetch).mock.calls[0][1]?.body));await w.get('[data-field="mode-clear"]').setValue();await w.get('[data-field="keep-legacy"]').setValue();expect(payload).toEqual({placement_version:3,target:{shelf_id:11,cell_id:null},idempotency_key:expect.any(String)});pending.resolve(res({}));await flushPromises();console.log('BUG303 mode reset blocks stale target, emitted request JSON snapshot stable during editing')})
})
